### ISSUE TITLE
update text-mining targeted association API

### ISSUE THREAD

**Issue by newgene** [biothings/pending.api#38]
Data Plugin: https://github.com/UCDenver-ccp/text_mining_targeted_association
API: https://biothings.ncats.io/text_mining_targeted_association

**Comment by erikyao** [comment]
Updated!

**Comment by erikyao** [comment]
## About Evidence List Threshold

In theory we can set a threshold of `4,900` entries for `association.evidence`  and `association.edge_attrbutes`. This threshold is for avoiding the `BSONObjectTooLarge` errors like below.

```bash
11:15:11 [2405493:MainThread] - text_mining_targeted_association_batch_1 - ERROR -- BSONObj size: 33408415 (0x1FDC59F) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: "0f13e9b7dd412a86b26e1ad10f2b6fdec7dfceaa2363404864b1e2aeb2bfee0e-false", full error: {'ok': 0.0, 'errmsg': 'BSONObj size: 33408415 (0x1FDC59F) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: "0f13e9b7dd412a86b26e1ad10f2b6fdec7dfceaa2363404864b1e2aeb2bfee0e-false"', 'code': 10334, 'codeName': 'BSONObjectTooLarge'}
Traceback (most recent call last):
  File "/opt/home/pending/venv/src/biothings/biothings/hub/dataload/uploader.py", line 51, in upload_worker
    return storage.process(data, batch_size)
  File "/opt/home/pending/venv/src/biothings/biothings/hub/dataload/storage.py", line 207, in process
    res = bob.execute()
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/bulk.py", line 709, in execute
    return self.__bulk.execute(write_concern, session=None)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/bulk.py", line 529, in execute
    return self.execute_command(generator, write_concern, session)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/bulk.py", line 360, in execute_command
    client._retry_with_session(
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1438, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1470, in _retry_internal
    return func(session, sock_info, retryable)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/bulk.py", line 354, in retryable_bulk
    self._execute_command(
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/bulk.py", line 310, in _execute_command
    result, to_send = bwc.execute(ops, client)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/message.py", line 950, in execute
    result = self.write_command(request_id, msg, to_send)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/message.py", line 1042, in write_command
    reply = self.sock_info.write_command(request_id, msg)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/pool.py", line 798, in write_command
    helpers._check_command_response(result, self.max_wire_version)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: BSONObj size: 33408415 (0x1FDC59F) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: "0f13e9b7dd412a86b26e1ad10f2b6fdec7dfceaa2363404864b1e2aeb2bfee0e-false", full error: {'ok': 0.0, 'errmsg': 'BSONObj size: 33408415 (0x1FDC59F) is invalid. Size must be between 0 and 16793600(16MB) First element: _id: "0f13e9b7dd412a86b26e1ad10f2b6fdec7dfceaa2363404864b1e2aeb2bfee0e-false"', 'code': 10334, 'codeName': 'BSONObjectTooLarge'}
11:15:11 [2405493:MainThread] - text_mining_targeted_association_batch_1 - ERROR -- Parameters:
name=text_mining_targeted_association
storage_class=<class 'biothings.hub.dataload.storage.IgnoreDuplicatedStorage'>
loaddata_func=<bound method Text_mining_targeted_associationUploader.load_data of <biothings.hub.dataplugin.assistant.AssistedUploader_text_mining_targeted_association object at 0x7f728bd55280>>
col_name=text_mining_targeted_association_temp_BfJ9F6C3
batch_size=10000
args=('/data/pending/datasources/text_mining_targeted_association/1.1',)
11:15:11 [2405493:MainThread] - text_mining_targeted_association_batch_1 - WARNING -- Could not pickle batch errors: cannot pickle '_thread.lock' object
```

I calculated the BSON object sizes, lengths of `association.evidence`, lengths of `association.edge_attrbutes` into a dataframe and computed the 99.999% quantiles, as below

```python
In [62]: df.head()
Out[62]:
   bson_size  evidence_len  edge_attr_len
0       5052             1              6
1      16036             4              9
2       5279             1              6
3      12081             3              8
4       5036             1              6

In [63]: df.quantile(q=0.99999)
Out[63]:
bson_size        1.668278e+07
evidence_len     4.921612e+03
edge_attr_len    4.926612e+03
Name: 0.99999, dtype: float64

In [64]: df.quantile(q=0.99999)["bson_size"] <= 16793600  # MongoDB BSON Object Limit
Out[64]: True
```

The quantiles show that less than 0.001% documents have more than 4,900 entries of `association.evidence`  and `association.edge_attrbutes`, and will exceeded the MongoDB BSON object size limits. 

The plugin developer @edgargaticaCU set the limit to `500` when generating the source data files (that is to say the threshold is not set in the `parser.py`)

**Comment by erikyao** [comment]
## Fix to the ES Mapping Error

Previously, both strings and float values both existed in `association.edge_attributes[<list_index>].value` and `association.edge_attributes[<list_index>].attributes[<list_index>].value`, but for ElasticSearch we must specify only one data type for each field.

[Commit 1546b41](https://github.com/UCDenver-ccp/text_mining_targeted_association/commit/1546b4126f699055e79582768e5afb4ff153d4a1) fixed this issue by adding `parse_float` and `parse_int` arguments to the `json.loads()` calls.

**Comment by erikyao** [comment]
Updated. See https://biothings.ncats.io/text_mining_targeted_association
