### ISSUE TITLE
Bug: setwise NGD hits the ES threshold on boolean clause number

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#83]
## Brief

- Introduced by [Issue#79](https://github.com/biothings/pending.api/issues/79) and [PR#81](https://github.com/biothings/pending.api/pull/81)
- Test case in [bte_trapi_query_graph_handler - PR#121](https://github.com/biothings/bte_trapi_query_graph_handler/pull/121)

## Cause

`pending_web` (testing env on `su06`) logs record that:

```python
[2022-08-26 13:36:08,824] {launcher.py:99} INFO - Server is running on "0.0.0.0:8000"...
[2022-08-26 13:36:08,843] {connections.py:25} INFO - Elasticsearch Package Version: 7.13.4
[2022-08-26 13:36:08,843] {connections.py:27} INFO - Elasticsearch DSL Package Version: 7.4.0
[2022-08-26 13:36:08,843] {connections.py:51} INFO - su03:9200: biothings_dev 6.8.23
[2022-08-26 13:36:37,151] {base.py:293} WARNING - POST http://su03:9200/semmeddb_20210831_r0y9dfts/_count [status:400 request:0.134s]
[2022-08-26 13:36:37,194] {web.py:1798} ERROR - Uncaught exception POST /semmeddb/query/ngd (172.29.80.35)
HTTPServerRequest(protocol='http', host='localhost:8000', method='POST', uri='/semmeddb/query/ngd', version='HTTP/1.1', remote_ip='172.29.80.35')
Traceback (most recent call last):
  File "/opt/home/pending/venv/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/opt/home/pending/pending.api/web/handlers/ngd.py", line 242, in post
    results = [res async for res in yield_results(arg_umls)]
  File "/opt/home/pending/pending.api/web/handlers/ngd.py", line 242, in <listcomp>
    results = [res async for res in yield_results(arg_umls)]
  File "/opt/home/pending/pending.api/web/handlers/ngd.py", line 221, in yield_results
    ngd = await self.ngd_service.calculate_ngd(term_pair)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 340, in calculate_ngd
    f_x, f_y, f_xy, n = await self._prepare_stats(term_pair)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 324, in _prepare_stats
    f_xy = await self.bipartite_doc_freq(term_pair)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 292, in bipartite_doc_freq
    doc_freq = await self.doc_stats_service.bipartite_doc_freq(term_pair)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 226, in bipartite_doc_freq
    count = await self._count_in_es(match)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 193, in _count_in_es
    count = await self.agent._count_in_es(match)
  File "/opt/home/pending/pending.api/web/handlers/service/ngd_service.py", line 151, in _count_in_es
    resp = await self.es_async_client.count(body=search.to_dict(), index=self.es_index_name)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/elasticsearch/_async/client/__init__.py", line 553, in count
    return await self.transport.perform_request(
  File "/opt/home/pending/venv/lib/python3.8/site-packages/elasticsearch/_async/transport.py", line 329, in perform_request
    raise e
  File "/opt/home/pending/venv/lib/python3.8/site-packages/elasticsearch/_async/transport.py", line 296, in perform_request
    status, headers, data = await connection.perform_request(
  File "/opt/home/pending/venv/lib/python3.8/site-packages/elasticsearch/_async/http_aiohttp.py", line 341, in perform_request
    self._raise_error(response.status, raw_data)
  File "/opt/home/pending/venv/lib/python3.8/site-packages/elasticsearch/connection/base.py", line 330, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'failed to create query: <long json omitted>
```

Root cause of the glitch can be found in ES logs:

```java
Caused by: org.apache.lucene.search.BooleanQuery$TooManyClauses: maxClauseCount is set to 1024
```

When computing the bipartite document frequencies, a stacked ES query can contain too many OR clauses. E.g. the 20th entry in the above example contains a UMLS C0003241 ("Antibody") which has 146 children. When its paird UMLS term has more than 3 children, their combination size would exceed 588 (147 * 4). Each combination brings in 2 OR clauses, so it exceeded the threshold of 1024 easily.

**Comment by erikyao** [comment]
Top 5 terms with the most children:

|Term/CUI           |Name                                  |No. of Children|
|-------------------|--------------------------------------|---------------|
|UMLS:C2628818      | unclassified Lepidoptera             | 43563         |
|UMLS:C1653016      | unclassified Cecidomyiidae           | 43333         |
|UMLS:C1624036      | unclassified Bacteria (miscellaneous)| 33165         |
|UMLS:C5482604      | unclassified Bacillus (in: Bacteria) | 29592         |
|UMLS:C5482798      | unclassified Pseudomonas             | 26609         |
