### ISSUE TITLE
`pending_web` error when restarting the PROD server

### ISSUE THREAD

**Issue by erikyao** [biothings/pending.api#90]
Error log:

```python
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:      ('/upheno_ontology/metadata/?', <class 'biothings.web.handlers.query.MetadataSourceHandler'>, {}),
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:      ('/upheno_ontology/spec/?', <class 'biothings.web.handlers.services.APISpecificationHandler'>, {}),
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:      ('/upheno_ontology/phenotype(?:/([^/]+))?/?', <class 'biothings.web.handlers.query.BiothingHandler'>, {'biothing_type': 'phenotype'}),
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:      ('/upheno_ontology/query/?', <class 'biothings.web.handlers.query.QueryHandler'>, {})]
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [INFO biothings.web.launcher:101] Server is running on "0.0.0.0:9080"...
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: /home/pending/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py:208: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:   warnings.warn(message, category=ElasticsearchWarning)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [INFO biothings.web.connections:26] Elasticsearch Package Version: 7.13.4
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [INFO biothings.web.connections:28] Elasticsearch DSL Package Version: 7.4.0
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [INFO biothings.web.connections:51] localhost:9200: pending_prod 7.17.0
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [ERROR asyncio:1285] Task exception was never retrieved
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     future: <Task finished coro=<BiothingsESMetadata._async_refresh() done, defined at /home/pending/venv/src/biothings/biothings/web/services/metadata.py:123> exception=AttributeError("'str' object has no attribute 'pop'",)>
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     Traceback (most recent call last):
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 127, in _async_refresh
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.update(biothing_type, info, count)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 104, in update
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         reader = _BiothingsESMetadataReader(_type, info, count)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 207, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         for index, index_info in info.items()
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 207, in <dictcomp>
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         for index, index_info in info.items()
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 270, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.mappings = _ESIndexMappings(mappings)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 353, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.enabled = mapping.pop('enabled', True)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     AttributeError: 'str' object has no attribute 'pop'
Aug 24 00:03:33 ip-172-31-1-254 python[27581]: [ERROR asyncio:1285] Task exception was never retrieved
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     future: <Task finished coro=<BiothingsESMetadata._async_refresh() done, defined at /home/pending/venv/src/biothings/biothings/web/services/metadata.py:123> exception=AttributeError("'str' object has no attribute 'pop'",)>
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     Traceback (most recent call last):
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 127, in _async_refresh
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.update(biothing_type, info, count)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 104, in update
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         reader = _BiothingsESMetadataReader(_type, info, count)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 207, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         for index, index_info in info.items()
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 207, in <dictcomp>
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         for index, index_info in info.items()
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 270, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.mappings = _ESIndexMappings(mappings)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:       File "/home/pending/venv/src/biothings/biothings/web/services/metadata.py", line 353, in __init__
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:         self.enabled = mapping.pop('enabled', True)
Aug 24 00:03:33 ip-172-31-1-254 python[27581]:     AttributeError: 'str' object has no attribute 'pop'
Aug 24 00:03:39 ip-172-31-1-254 python[27581]: [INFO tornado.access:2243] 200 GET /semmeddb/query/ngd?umls=C0599779,C0683949&expand=both (24.7.27.31) 37.67ms
```

**Comment by erikyao** [comment]
Fixed with Biothings API update.
